feature: add attribute flag for allowing digital signatures
sinet/validation pull request #34
Opened 2017-06-20 04:58 UTC by Darbiol

[S-08693](https://www12.v1host.com/SchoolImprovementNetwork47/story.mvc/Summary?oidToken=Story:169233)

2017-06-20 05:01 UTC, Darbiol commented
@mashu-daishi @MrAnderson0309 @hanchan07 can you please take a look at this PR, see if you're OK with this

2017-06-21 14:07 UTC, mashu-daishi requested changes

2017-06-21 14:07 UTC, mashu-daishi commented on schemas/observation/observation.js
> +		'signature' : Joi
This should probably be keyed the same as the index.js file (it's listed as `digitalSignature` there).

2017-06-21 14:07 UTC, mashu-daishi commented on schemas/observation/digital-signature.js
> +			.optional()
Are you allowing for empty arrays within the `observer` and `observee` fields? I believe listing the items as `optional()` allows for that.

2017-06-21 14:07 UTC, mashu-daishi commented on schemas/observation/digital-signature.js
> +	'observee' : Joi
Just to confirm: the only **two** people that will be digitally-signing an observation are the observer and the observee, correct?

2017-06-21 14:07 UTC, mashu-daishi commented on schemas/observation/digital-signature.js
> +var signatureInfo = {
Should all three properties be optional? It seems that, if you pass any of them, you should be passing all of them.

2017-06-21 14:07 UTC, mashu-daishi commented on schemas/observation/digital-signature.js
> +	'date'    : Joi.date().optional().description( 'The date of which the user signed the observation' ),
You're probably going to want to type this as `Joi.date().timestamp()...`. We'll want to ensure time is included with the date.

2017-06-21 23:09 UTC, Darbiol commented on schemas/observation/digital-signature.js
> +	'observee' : Joi
yes

2017-06-21 23:38 UTC, Darbiol commented on schemas/observation/digital-signature.js
> +			.optional()
yes we are allowing empty arrays

2017-06-22 00:01 UTC, Darbiol commented
@mashu-daishi @hanchan07 @MrAnderson0309 i've updated the PR, can you take a look at it again please

2017-06-22 02:02 UTC, mashu-daishi commented on schemas/observation/digital-signature.js
> +			.optional()
What's the purpose of the empty array? If it's empty, why not just not save the key?

2017-06-22 02:05 UTC, mashu-daishi approved these changes

2017-06-22 02:14 UTC, Darbiol commented on schemas/observation/digital-signature.js
> +			.optional()
so that we can ensure that the output will always be an array

2017-06-22 02:26 UTC, merged